version: '3.4'

services:
  minecraftapi.api:
    image: ${DOCKER_REGISTRY-}minecraftapiapi
    build:
      context: .
      dockerfile: src/MinecraftApi.Api/MinecraftApi.Api/Dockerfile
    environment:
        - DB_PW
    depends_on:
        - db
  db:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - mssql-server-minecraftapi-data:/var/opt/mssql/data
    environment:
        SA_PASSWORD: "${DB_PW}"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Enterprise"
    ports:
      - "1433:1433"
volumes:
    mssql-server-minecraftapi-data: {}